# Generated by Django 3.1.4 on 2020-12-03 06:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201202_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistration',
            name='pan_number',
            field=models.CharField(default='', max_length=10, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
    ]
