# Generated by Django 3.1.4 on 2020-12-03 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_userregistration_pan_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistration',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='', max_length=1),
        ),
    ]
